noun = input('chose a noun: ')
adj = input('chose an adjective: ')
verb = input('chose a verb: ')
verb2 = input('chose another verb: ')
FP = input('chose a famous person: ')
print('{} is so amazing! It makes me  so {} all the time because I love to {}. Stay hydrated and {} like you are {}'.format(noun,adj,verb,verb2,FP))